name: Flask CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build ./backend --file backend/Dockerfile --tag myusername/myapp:${{ github.sha }}

    - name: Push the Docker image to Docker Hub
      run: docker push myusername/myapp:${{ github.sha }}

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Pull the Docker image from Docker Hub
      run: docker pull myusername/myapp:${{ github.sha }}

    - name: Run tests
      run: docker run myusername/myapp:${{ github.sha }} /bin/sh -c "pytest"
